datasets:
  # class_name, data_name & data_sampling_ratio are not used but need to be passed to avoid errors
  - class_name: MegatronDataset
    data_name: Megatron
    data_sampling_ratio: 1
    class_args:
      eval_steps: 2
      data_cache_path: cache
      # Option 1: data loading using --data-path with single file
      data_path:
        - /proj/datasets/training_data_starcoder_cleaned_0324/dataset=wikimedia-1-en
      split: 100,0,0
      sequence_length: 4096

tokenizer_args:
  tokenizer_name: bigcode/starcoder

model_args:
  model_class: AutoModelForCausalLM
  pretrained_config:
    activation_function: swiglu
    add_bias: false
    attn_pdrop: 0
    embd_pdrop: 0
    resid_pdrop: 0
    initializer_range: 0.1
    layer_norm_epsilon: 1e-05
    model_type: rnn_dolomite
    n_embd: 1024
    n_head: 8
    n_inner: 2560
    n_layer: 24
    n_positions: 4096
    attention_patterns: dddddadddddadddddaddddda
    normalization_function: rmsnorm
    position_embedding_type: nope
    rope_theta: 10000
    attention_head_type: mha
    scale_attn_weights: true
    vocab_size: 50304
    m_width: 10
    m_emb: 12
    m_residual: 0.22
    init_method: mup
    tie_word_embeddings: true
  attention_implementation: flash_attention_2

tuning_args:
  tuning_method: pretraining

save_args:
  save_path: /proj-3500/checkpoints/yikang/debug
  save_interval: 1000

logging_args:
  log_interval: 10

training_parameters:
  num_training_steps: 30000
  eval_interval: 100000
  micro_batch_size: 8
  gradient_accumulation_steps: 16
  eval_during_training: false

optimizer_args:
  params_group_method: mup
  class_name: TorchAdamW
  class_args:
    lr: 0.01
    weight_decay: 0.1
    betas:
      - 0.9
      - 0.95
    eps: 1e-10

lr_scheduler_args:
  lr_decay_style: exponential
  num_warmup_steps: 2500
  num_constant_steps: 25000
  num_decay_steps: 2500

mixed_precision_args:
  dtype: bf16

distributed_args:
  distributed_backend: torch

