datasets:
  - class_name: SST2Dataset
    data_name: sst2
    input_format: "Classify the sentiment of the sentence:\n__input__\nSentiment:"
    output_format: " __output__"
    data_sampling_ratio: 1
    max_input_tokens: 1024
    max_output_tokens: 128

load_args:
  load_path: checkpoints/full_finetuning
  iteration: 4000

generation_parameters:
  batch_size: 8
  do_sample: false
  max_new_tokens: 100

output_dir: outputs
